---
layout: post
title: 'Swift: Various Special Headers '
date: '2015-11-02T10:43:00.003-08:00'
author: Scott McCoy
tags: 
modified_time: '2015-11-02T10:43:37.191-08:00'
blogger_id: tag:blogger.com,1999:blog-250956833460526415.post-86449267551797869
blogger_orig_url: https://scotthmccoy.blogspot.com/2015/11/swift-various-special-headers.html
---

<br /><ol><li><b>ProductModuleName-Bridging-Header.h</b>: Import every Objective-C header I want to expose to Swift. Make sure the "Objective-C Bridging Header" build setting has a path to the file (it'll halt compilation if it doesn't)</li><li><b>Foo-Swift.h</b>: This is the opposite of the bridging header. It exposes Swift classes to Obj-c that are either marked @objc or are declared as subclasses of ObjC classes (frequently NSObject). This header is generated by Xcode, you don't need to generate it or maintain yourself. It does sometimes seem like it can get out of sync, though. Usually a clean re-build fixes this.</li><li><b>FrameworkName.h</b>: This is an umbrella header for your framework. Inside you should import all the public headers of your framework using statements like <b>#import <openxsdkcore ublicheader.h=""></openxsdkcore></b>. I think you may also have to add something like the following, but I am not sure:</li><ol><li>//! Project version number for OpenXSDKCore.</li><li><span class="s1">FOUNDATION_EXPORT </span><span class="s2">double</span><span class="s1"> OpenXSDKCoreVersionNumber;</span></li><li>//! Project version string for OpenXSDKCore.</li><li><span class="s1">FOUNDATION_EXPORT </span><span class="s2">const</span><span class="s1"> </span><span class="s2">unsigned</span><span class="s1"> </span><span class="s2">char</span><span class="s1"> OpenXSDKCoreVersionString[];</span></li></ol></ol>