---
layout: post
title: Best Practices for exposing an enum from Swift to OBJC
date: '2017-10-13T15:09:00.002-07:00'
author: Scott McCoy
tags: 
modified_time: '2017-10-13T15:09:50.904-07:00'
blogger_id: tag:blogger.com,1999:blog-250956833460526415.post-3618342861431172512
blogger_orig_url: https://scotthmccoy.blogspot.com/2017/10/best-practices-for-exposing-enum-from.html
---

Given:<br />1. Enums have to be Int to be exposed to obj-C.<br />2. Vars and Functions defined on them will not be visible to obj-c.<br />3. It's nice to be able to use .description and string interpolation<br /><br />This is the best I've found so far:<br /><br /><div class="p1"><span class="s1">@objc</span><span class="s2"> </span><span class="s1">public</span><span class="s2"> </span><span class="s1">enum</span><span class="s2"> OXMLogLevel: </span>Int<span class="s2">, </span>CustomStringConvertible<span class="s2"> {</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span><span class="s1">case</span> info = <span class="s3">0</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span><span class="s1">case</span> warn = <span class="s3">1</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span><span class="s1">case</span> error = <span class="s3">2</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span><span class="s1">case</span> none = <span class="s3">3</span></div><div class="p3"><span class="Apple-converted-space">&nbsp;&nbsp; &nbsp;</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span><span class="s1">public</span> <span class="s1">var</span> description: <span class="s4">String</span> {</div><div class="p4"><span class="s2"><span class="Apple-converted-space">&nbsp; &nbsp; &nbsp; &nbsp; </span></span><span class="s1">return</span><span class="s2"> </span>OXMFunctions<span class="s2">.</span><span class="s5">toString</span><span class="s2">(</span><span class="s1">self</span><span class="s2">)</span></div><div class="p2"><span class="Apple-converted-space">&nbsp; &nbsp; </span>}</div><div class="p1">    <style type="text/css">p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #703daa; background-color: #ffffff} p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff} p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff; min-height: 13.0px} p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #4f8187; background-color: #ffffff} span.s1 {color: #ba2da2} span.s2 {color: #000000} span.s3 {color: #272ad8} span.s4 {color: #703daa} span.s5 {color: #31595d} </style>           </div><div class="p2">}</div><style type="text/css">p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff} p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px Menlo; color: #000000; background-color: #ffffff; min-height: 13.0px} span.s1 {color: #ba2da2} span.s2 {color: #703daa} span.s3 {color: #272ad8} span.s4 {color: #31595d} span.s5 {color: #d12f1b} </style>