---
layout: post
title: Local Webserver on iOS
date: '2018-10-04T11:11:00.001-07:00'
author: Scott McCoy
tags: 
modified_time: '2018-10-04T11:11:52.365-07:00'
blogger_id: tag:blogger.com,1999:blog-250956833460526415.post-7301027556831929326
blogger_orig_url: https://scotthmccoy.blogspot.com/2018/10/local-webserver-on-ios.html
---

<br />Seems like if the baseURL points at the bundle, we can load local content.<br />Since OpenXSDKCore is a framework, this might be a security issue - don't want ads getting access to Info.plist, lets say.<br /><br />iOS11 has an interception thing on WKWebView but that limits testability to iOS 11.<br /><br />Maybe a local webserver is the only way!<br /><br /><span style="white-space: pre;"> </span>Kitura is stuffy and academic<br /><span style="white-space: pre;"> </span>https://developer.ibm.com/swift/2017/03/13/kitura-ios/<br /><br /><span style="white-space: pre;"> </span>Embassy is Envoy's thing. It's kind of lame<br /><span style="white-space: pre;"> </span>https://github.com/envoy/Embassy<br /><br /><span style="white-space: pre;"> </span>Swifter is pretty straightforward:<br /><br /><span style="white-space: pre;">  </span>let server = demoServer(Bundle.main.resourcePath!)<br /><span style="white-space: pre;">  </span>server["/:path"] = shareFilesFromDirectory(self.path)<br /><span style="white-space: pre;">  </span>try server.start(9080)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <br /><span style="white-space: pre;">  </span>let myRequest = NSURLRequest(url: NSURL(string: "http://localhost:9080") as! URL)<br /><span style="white-space: pre;">  </span>self.webView.loadRequest(myRequest as URLRequest)<br /><span style="white-space: pre;">    </span><br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br /><br />Regardless a web server running in the app is going to require being able to bind to a different port than 80, which means having to change OXMServerConnection:<br /><br />You can bind to port 80 on the device's IPv4 interface but not the IPv6 interface and not in the simulator. You'll need to modify your socket code to only listen on the IPv4 interface, for the simulator you can conditionally use a different port:<br />#if TARGET_IPHONE_SIMULATOR<br />&nbsp; &nbsp; [httpServer setPort:8080];<br />#else<br />&nbsp; &nbsp; [httpServer setPort:80];<br />#endif<br />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br /><br /><br />Haven’t tried loading the file and replacing URLs to point at the bundle and then passing that to MockServer. That could totally work!